{
    'name': 'Library Management',
    'version': '1.0',
    'summary': 'Manage books, authors, and book loans in a library',
    'category': 'Extra Tools',
    'author': 'Abdullah AbuSoboh',
    'depends': ['base', 'contacts', 'account', 'product'],
    'data': [
'security/ir.model.access.csv',
        'views/library_menus.xml',
        'views/book_views.xml',
        'views/author_views.xml',
        'views/book_lending_views.xml',
    'views/membership_request_action.xml',
    'report/membership_report.xml',
    'report/report_membership_single.xml',
    'report/membership_report_template.xml',
'views/membership_request_view.xml',
    'views/res_partner_view.xml',
'data/sequence.xml',
'views/invoicing_menus.xml',
        'data/product_data.xml',
    'views/membership_report_template.xml',
    'views/membership_report_action.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}

